# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 11:22
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='art',
            name='cover',
            field=models.ImageField(null=True, upload_to='art/images', verbose_name='封面'),
        ),
    ]
