# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20180814_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='publish_data',
            new_name='publish_date',
        ),
    ]
