# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 12:12
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20180814_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='art',
        ),
        migrations.AddField(
            model_name='art',
            name='chapter',
            field=models.CharField(default=0, max_length=100, verbose_name='章节'),
        ),
        migrations.AddField(
            model_name='art',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='正文'),
        ),
        migrations.AddField(
            model_name='art',
            name='roll',
            field=models.CharField(default=0, max_length=50, verbose_name='卷'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Roll',
        ),
    ]
