# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 12:20
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_auto_20180814_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=50, verbose_name='章节')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='正文')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 't_chapter',
            },
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_name', models.CharField(max_length=50, verbose_name='卷名')),
            ],
            options={
                'verbose_name': '卷',
                'verbose_name_plural': '卷',
                'db_table': 't_roll',
            },
        ),
        migrations.RemoveField(
            model_name='art',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='art',
            name='roll',
        ),
        migrations.AddField(
            model_name='roll',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Art'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Roll'),
        ),
    ]
